### ISSUE TITLE
About Paper

### ISSUE THREAD

**Issue by henrycjh** [yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition#1]
Thanks for your great work! The paper link in readme is broken, and I cannot find it through google. Is there any way I could find the paper now?

**Comment by yuyujunjun** [comment]
The website will not release the papers until the conference has been completed. 
You can find the paper in "[http://www.cad.zju.edu.cn/home/jin/sig20232/SigRSMT2023.htm](http://www.cad.zju.edu.cn/home/jin/sig20232/SigRSMT2023.htm)"
Besides, I will promptly upload it to arXiv.
