### ISSUE TITLE
Question on Distinguishability of Styles

### ISSUE THREAD

**Issue by UI233** [yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition#10]
Greetings! Thanks for you excellent work!

I am a bit confused about the "Stylized" part of your paper, it would be too kind if you can answer my question.

While trying to implement the sampler, I have encountered a weird phenomenon the **style encoder** degenerate to a constant function when the sampler network converges but the overall generation performance is OK. After reading your paper, I came up with a question that whether it is normal for the network to behave like that because there exhbit no difference between styles in the training set.

For every motion sequence *S* in the dataset, the ground truth of next frame prediction is deterministic. As a result, there is no pair of data such that P(S | s^0, s^T, h^0, k^1) != P(S | s^0, s^T, h^0, k^2) which means the style code k^i could have no impact on the motion infilling.  It is ok for the sampler to ignore the style information. 

However, in your results, your network actually distinguishes different styles quite well. So I wonder if I have missed some important part of your work and I would appreciate it if you cloud provide some information.

**Comment by yuyujunjun** [comment]
Thank you for your interests. Most of your observations are right:
1. The style encoder doesn't affect the results much.
2. Even the CVAE network by Tang et al. 2022, P(S|s0,s^T,h^0) is enough for predicting a "stylized" motion, **only if s0,s^T,h^0 have the same distribution as the training dataset.** We don't distinguish different styles, but predict the most probable next frame. If the past frames are stylized, the next frame should be stylized.

However, 
1. the style encoder indeed has its impact when network cannot distinguish style from s0,s^T and h^0. 
   "As a result, there is no pair of data such that P(S | s0, s^T, h^0, k^1) != P(S | s0, s^T, h^0, k^2)", but there may be a pair of data such that s0, s^T, h^0 are similar but k and S are different.
2. If we change the time duration or the target frame location, the distribution may be different from the training set. In such cases, the network will be unable to predict the "stylized" frame. Hence, the phase vector is added to ensure the consistency of the dynamic of the next frame with the past.

See our video for more details. http://www.cad.zju.edu.cn/home/jin/sig20232/demo.mp4

**Comment by UI233** [comment]
Thanks for your answer! 

So I think the dataset splitting will hugely affect the behavior of style encoder. If I split the dataset carelessly and there is no a pair of data that s0, s^T, h^0 are similar but k and S are different, the sampler encoder will easily degenerate to a constant funciton. I will check my dataloader more carefully.

Again, thanks for your time.

**Comment by yuyujunjun** [comment]
Check if your network can distinguish "left foot bounce" style. In our experiments, iithout style encoder, the network treats "left foot bounce" style as the netural walking.
