### ISSUE TITLE
Software to visualise

### ISSUE THREAD

**Issue by mshooter** [yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition#11]
Great work! 

I was wondering which software you were using to visualise the skeletons? 
Thank you!

**Comment by yuyujunjun** [comment]
i am used to importing bvh file in blender

Xiangjun Tang
________________________________
发件人: Moira Shooter ***@***.***>
发送时间: Wednesday, November 22, 2023 4:24:59 AM
收件人: yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition ***@***.***>
抄送: Subscribed ***@***.***>
主题: [yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition] Software to visualise (Issue #11)


Great work!

I was wondering which software you were using to visualise the skeletons?
Thank you!

―

**Comment by mshooter** [comment]
Thank you!
