### ISSUE TITLE
您好，请问motion_statistics.dat这个文件怎么生成的？

### ISSUE THREAD

**Issue by CFHH** [yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition#13]
train_transitionNet.py有用到，但是按照readme里的步骤执行下来，并没有此文件，搜索也只有此处有“motion_statistics”。

**Comment by yuyujunjun** [comment]
这个文件已经在MotionData/100STYLE中。这个文件记录的是数据的均值和方差，用于normalized，你也可以自己生成。

**Comment by CFHH** [comment]
> 这个文件已经在MotionData/100STYLE中。这个文件记录的是数据的均值和方差，用于normalized，你也可以自己生成。

谢谢，看到了，这个具体怎么生成，有代码吗？
