### ISSUE TITLE
训练时间

### ISSUE THREAD

**Issue by Jixiii** [yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition#15]
请问一下训练时间需要多久，配置是什么。styleVAE的epoch应该选择多少

**Comment by yuyujunjun** [comment]
StyleVAE基本上训练到曲线不再下降即可，可以稍作延长，大概150个epoch，也可以更多，取决于采样表现。整个in-between框架我们习惯训练到350k次迭代，和Real-time Controllable Motion Transition for Characters以及robust motion in-between工作保持一致。

**Comment by Jixiii** [comment]
好的，感谢
