### ISSUE TITLE
关于Predict_Phase = True模式下，PredictInitialState出现的问题

### ISSUE THREAD

**Issue by wangziming0527** [yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition#17]
为了use this method on key frames without a corresponding phase vector，我按照项目描述训练了phase predictor，但测试时收到报错：
RuntimeError: Calculated padded input size per channel: (1). Kernel size: (3). Kernel size can't be greater than actual input size。

经检查，输入x = torch.Size([1, 1024, 5])，而PredictInitialState模型架构为
self.conv_layer = nn.Sequential(
            nn.Conv1d(1024,1024,5),
           # nn.AvgPool1d(2),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Conv1d(1024, 1024, 3),
          #  nn.AvgPool1d(2),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Conv1d(1024, 1024, 2),
            nn.ReLU()
        )

这样经过第一个卷积层后，Sequence_length会变为1，小于第二个卷积层的卷积核大小
请问应该如何解决此问题？

**Comment by yuyujunjun** [comment]
过去帧的长度是固定的，应该是9还是10帧

**Comment by wangziming0527** [comment]
解决了，谢谢
