### ISSUE TITLE
Question about the style

### ISSUE THREAD

**Issue by henrycjh** [yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition#2]
Greetings! 
If I remove all the parts about style in the entire pipeline ( everything about phase and style encoder ), will the quality of generated motions degrade?

**Comment by yuyujunjun** [comment]
Very good question! 

The motion quality, including foot skating metrics and naturalness of motion, is not compromised; however, the style cannot be guaranteed absolutely.

Specifically, after selecting a style sequence from the test set and removing the middle section, it's possible to synthesize the missing part with the same style; however, if the time duration or target frame position is modified, there is no assurance that the generated results will remain in the same style.

In fact, it's very similar to our previous paper, [Real-time Controllable Motion Transition for Characters], you could see the motion quality at  " [https://www.youtube.com/watch?v=xgpw6WXs3Ig&t=6s&ab_channel=HeWang](https://www.youtube.com/watch?v=xgpw6WXs3Ig&t=6s&ab_channel=HeWang)"

**Comment by henrycjh** [comment]
Thanks for your quick reply!  I will check it later.
By the way, could you please provide a requirements.txt so that I could set up the environment for training?

**Comment by yuyujunjun** [comment]
ok
