### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by henrycjh** [yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition#4]
`Missing logger folder: tensorboard_logs/Transitionv2_style100/myResults
Traceback (most recent call last):
  File "/workspace/RSMT-Realtime-Stylized-Motion-Transition/train_transitionNet.py", line 192, in <module>
    training_style100_phase()
  File "/workspace/RSMT-Realtime-Stylized-Motion-Transition/train_transitionNet.py", line 127, in training_style100_phase
    stat = style_loader.load_part_to_binary("motion_statistics")
  File "/workspace/RSMT-Realtime-Stylized-Motion-Transition/src/Datasets/Style100Processor.py", line 116, in load_part_to_binary
    f = open(path + '/' + filename + ".dat", "rb")
FileNotFoundError: [Errno 2] No such file or directory: './/motion_statistics.dat'`
It seems that you forgot to upload motion_statistics.dat，cause I cannot find the key words ‘motion_statistics’ in any other files

**Comment by yuyujunjun** [comment]
Thank you! 

Uploaded.

**Comment by Eagleton** [comment]
How to generate a new motion_statistics.dat if I change the skeleton?

**Comment by yuyujunjun** [comment]
The code can be found in [process_dataset.py](https://github.com/yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition/blob/main/process_dataset.py).

**Comment by Eagleton** [comment]
May be I should do the following:
1. load the skeleton to skeleton, load train_binary.dat, test_binary.dat to train_dict, test_dict
2. append the train_dict[style_key][content_key]['offsets'] to list o, train_dict[style_key][content_key]['hips'] to list h, train_dict[style_key][content_key]['quats'] to list q. And do the same thing to test_dict
3. create a TransitionProcessor obj, use it's __call__ function to get the result dict
4. save the dict to motion_statistics.dat
Is the above correct?

**Comment by yuyujunjun** [comment]
There are many details in dealing with the data and I can't remember them all. 
The simplist way is locate new dataset to the same folder architecture as the style100 dataset and treat it as style100 dataset.
If you need reference, StyleLoader class may be helpful. 
If you just want to calculate new motions statistics for new dataset, calculate_statistic may be helpful.
