### ISSUE TITLE
moe_decoder.decoder has no attribute decoder

### ISSUE THREAD

**Issue by HennyWen** [yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition#5]
In train_transitionNet.py line 105
def training_style100_phase():
from src.Datasets.StyleVAE_DataModule import StyleVAE_DataModule
from src.Net.TransitionPhaseNet import TransitionNet_phase,Application_phase 
prefix = "Transitionv2"
data_set = "style100"
prefix += "_" + data_set
args, trainer_dict, ckpt_path = create_common_states(prefix)
moe_net = torch.load(args.moe_model)

here torch.load returns a dict object but in TransitionPhaseNet.py line 240 here directly access the decoder in a dict object 
`        self.decoder = moe_decoder.decoder`
which raise the error

**Comment by yuyujunjun** [comment]
After executing "python train_styleVAE.py --test --version YOUR_VERSION --epoch YOUR_EPOCH", the program generates a model by torch.save() in the same folder as the *.ckpt. Could you please try to load this model first?

**Comment by HennyWen** [comment]
Yes I do load it from a ckpt file but  the problem is  by using `torch.load` this function returns a dict object which has no decoder attribute

(RSMT) ➜  RSMT-Realtime-Stylized-Motion-Transition git:(main) ✗ python train_transitionNet.py --moe_model ./results/StyleVAE2_style100/myResults/0/last.ckpt
Global seed set to 3407
Missing logger folder: tensorboard_logs/Transitionv2_style100/myResults
Traceback (most recent call last):
  File "/mnt/d/RSMT-Realtime-Stylized-Motion-Transition/train_transitionNet.py", line 192, in <module>
    training_style100_phase()
  File "/mnt/d/RSMT-Realtime-Stylized-Motion-Transition/train_transitionNet.py", line 130, in training_style100_phase
    model = TransitionNet_phase(moe_net, data_module.skeleton, pose_channels=9,stat=stat ,phase_dim=phase_dim,
  File "/mnt/d/RSMT-Realtime-Stylized-Motion-Transition/src/Net/TransitionPhaseNet.py", line 240, in __init__
    self.decoder = moe_decoder.decoder
AttributeError: 'dict' object has no attribute 'decoder'

**Comment by yuyujunjun** [comment]
Try to load the model named by m_save_model_xxx. It located the same folder as **.ckpt

**Comment by HennyWen** [comment]
I check the folder and there is no m_save_model_xxx, I use the pytorchlightning load_from_checkpoint instead of torch.load and this worked

**Comment by yuyujunjun** [comment]
It's ok for using load_from_checkpoint. 
The m_save_model_xxx is generated by running 
```
python train_styleVAE.py --test --version YOUR_VERSION --epoch YOUR_EPOCH
```
you may miss the validation step.

**Comment by HennyWen** [comment]
Thanks for this information, I do skip this validation step for quicker running the whole process
