### ISSUE TITLE
The phase predictor

### ISSUE THREAD

**Issue by HennyWen** [yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition#6]
Here in the readme file for genreal applications i.e generating transistion for key frames without a phase vetector, the phase vector of the key frame should be obtained via a phase preditor first. My question is, should this phase prediction be in an auto-regressive manner as well? for example we first predict the phase for key frame t1 then phase for t1+1 and so on

**Comment by yuyujunjun** [comment]
Good question.

I don't think we need autoregressive models there, although we haven't conducted any experiments to support my assumption. 
From my opinion, the updating of a phase vector does not lead to a significant deviation from the original phase. If the first phase vector is incorrect, autoregressive manner may not correct it within few steps.  Predicting phase while utilizing all available information seems a more viable option. 

It's important to note that we have not yet found a viable method to replace the phase without compromising the impact. Therefore, any proposed method is worth exploring.
