### ISSUE TITLE
About sampler training

### ISSUE THREAD

**Issue by Eagleton** [yuyujunjun/RSMT-Realtime-Stylized-Motion-Transition#9]
Great work! But I have a question about the training of sampler. I trained the sampler on a new dataset(https://github.com/ubisoft/ubisoft-laforge-animation-dataset), but the loss seems not to converge and the loss curve is oscillating. I wonder if it's the reason of dataset and what the reason could be.

**Comment by yuyujunjun** [comment]
Thank you for your interest. 
We've trained Lafan1 Dataset last year in the paper "Real-time controllable motion transition for characters".
As far as I know, the scale of data in Lafan1 Dataset is different from the data in 100Style so the loss weight may need to be adjusted accordingly.
Another possible problem is that the manifold haven't not been trained well. Have you validated the manifold model?

**Comment by Eagleton** [comment]
Thank you very much! I think I should validated the manifold model and adjust the loss weights again.
And When I learned the code, there are some other questions:
1. In shift_running function of TransitionPhaseNet.py(line 315), why the start index is 1? Could it be 0?
2. The class PredictInitialState in TransitionPhaseNet.py seems to be hardly coding and the time dimension input to it should be 8, which means I must have 8 frame data?
3. When you sample the data, it seems that you only used 61 frames of 120 frame, I want to know the design reason.

**Comment by yuyujunjun** [comment]
Sorry for not responding eariler.
1. Velocity is calculated by the difference between two neighbor frames and the 0-th frame does not have the velocity.
2. We hope that the PredictInitialState module plays the same role as LSTM network, which takes 8 frames as the past context. 
3. 2 seconds (60) sequence seems be enough for presenting the motion style. 
Hope it's helpful!

**Comment by Eagleton** [comment]
Thank you very much!
